/**
 * Pedagogist Agent - Educational Idea Generation Specialist
 * 
 * This agent is responsible for creating high-quality educational problems
 * and learning objectives. It focuses on curriculum design and pedagogical
 * best practices, generating ideas that will be implemented by the Coder Agent.
 * 
 * Key Responsibilities:
 * - Analyze user prompts for educational value
 * - Generate clear learning objectives
 * - Design appropriate difficulty progression
 * - Ensure problems are educational, not just technical
 */

import type { 
  GenerationContext,
  CapsuleLanguage,
  CapsuleDifficulty,
  CapsuleType 
} from '../types/base-capsule'

import { isDataAnalysisContext, buildDatasetCatalogPrompt } from '../datasets/universal-datasets'

// ===== PEDAGOGIST INTERFACES =====

/**
 * Educational idea generated by the Pedagogist
 */
export interface CapsuleIdea {
  title: string
  description: string
  learning_objectives: string[]
  prerequisites: string[]
  difficulty_rationale: string
  educational_value: number        // 0-1 score
  estimated_time_minutes: number
  target_audience: string
  key_concepts: string[]
}

/**
 * Pedagogical analysis of user input
 */
export interface PedagogicalAnalysis {
  user_intent: string
  educational_gaps: string[]
  suggested_improvements: string[]
  complexity_level: 'too_simple' | 'appropriate' | 'too_complex'
  recommendations: string[]
}

/**
 * Configuration for pedagogist behavior
 */
export interface PedagogistConfig {
  focus_on_fundamentals: boolean
  encourage_exploration: boolean
  provide_context: boolean
  use_real_world_examples: boolean
  difficulty_bias: 'easier' | 'standard' | 'harder'
}

// ===== PEDAGOGIST AGENT IMPLEMENTATION =====

export class PedagogistAgent {
  private config: PedagogistConfig
  private aiService: any // Will be injected

  constructor(config: Partial<PedagogistConfig> = {}) {
    this.config = {
      focus_on_fundamentals: true,
      encourage_exploration: true,
      provide_context: true,
      use_real_world_examples: true,
      difficulty_bias: 'standard',
      ...config
    }
  }

  /**
   * CALL 1: The "Pedagogist" Agent - Brainstorm ONE high-quality problem idea
   * Job: Focus ONLY on educational idea generation, nothing else
   */
  async generateIdea(context: GenerationContext): Promise<CapsuleIdea> {
    const difficultySpec = this.getDifficultySpec(context.difficulty)

    // Inject universal dataset catalog for data analysis capsules
    const datasetBlock = isDataAnalysisContext(context.language, context.userPrompt)
      ? `\n${buildDatasetCatalogPrompt()}\n`
      : ''

    const prompt = `You are an expert curriculum designer. A user wants a '${context.difficulty}' '${context.language}' problem about '${context.userPrompt}'.

=== DIFFICULTY SPECIFICATION: ${context.difficulty.toUpperCase()} ===
${difficultySpec}
=== END DIFFICULTY SPECIFICATION ===${datasetBlock}

Brainstorm ONE single, unique, high-quality problem idea that STRICTLY follows the difficulty specification above.
${datasetBlock ? `The problem MUST use one of the Universal Datasets listed above. Reference the actual column names in your description.
CRITICAL: Only these CSV files exist in the execution environment — apple_global_sales_dataset.csv and spotify-tracks-dataset.csv. NEVER reference any other CSV files. Do NOT suggest creating test/mock/sample CSVs.` : ''}

Return JSON with this exact structure:
{
  "title": "Short, descriptive title",
  "description": "2-3 sentence problem description",
  "learning_objectives": ["What will students learn?", "What skills will they practice?"],
  "prerequisites": ["What should they know first?"],
  "difficulty_rationale": "Explain how this problem fits the ${context.difficulty} difficulty spec above",
  "educational_value": 0.85,
  "estimated_time_minutes": ${context.difficulty === 'easy' ? 10 : context.difficulty === 'medium' ? 25 : 45},
  "target_audience": "${context.difficulty === 'easy' ? 'beginner' : context.difficulty === 'medium' ? 'intermediate' : 'advanced'} ${context.language} learners",
  "key_concepts": ["main concept 1"${context.difficulty !== 'easy' ? ', "main concept 2"' : ''}${context.difficulty === 'hard' ? ', "main concept 3"' : ''}]
}`

    try {
      const messages = [{ role: 'user' as const, content: prompt }]
      const response = await this.aiService.generateJSON(messages, {
        temperature: 0.5,
        max_tokens: 500
      }) as CapsuleIdea

      // Basic validation only
      if (!response.title || !response.description || !response.learning_objectives?.length) {
        throw new Error('Generated idea is incomplete')
      }

      return response

    } catch (error) {
      console.error('Pedagogist Agent failed:', error)
      throw new Error(`Failed to generate educational idea: ${error instanceof Error ? error.message : String(error)}`)
    }
  }

  /**
   * Get structured difficulty specification for the 5-axis framework.
   * This is the single source of truth for what EASY/MEDIUM/HARD means.
   */
  private getDifficultySpec(difficulty: string): string {
    switch (difficulty) {
      case 'easy':
        return `CONCEPTUAL LOAD: ONE core concept only. No concept mixing.
BOILERPLATE: Full function signature with clear comments and variable names provided.
TEST STRUCTURE: 2 visible tests + 1 simple hidden test = 3 total.
EDGE CASES: Only normal inputs. No null, no empty, no extreme values.
PERFORMANCE: Small input size. No optimization requirement.
TIME: 5-15 minutes to solve.
EXAMPLE PROBLEM SHAPE: "Write a function that returns the sum of numbers in a list."
DO NOT make this problem require combining multiple concepts. Keep it to ONE idea.`

      case 'medium':
        return `CONCEPTUAL LOAD: 2 related concepts that must be combined (e.g., filtering + aggregation).
BOILERPLATE: Function signature given with minimal comments. Some thinking required.
TEST STRUCTURE: 2 visible tests + 2 hidden tests + 1 edge case test = 5 total.
EDGE CASES: Include empty input, negative numbers, null values.
PERFORMANCE: Moderate dataset size. Inefficient solution may pass but is suboptimal.
TIME: 20-30 minutes to solve.
EXAMPLE PROBLEM SHAPE: "Given sales data, return total revenue per region excluding refunded orders."
The student must combine filtering and grouping to solve this.`

      case 'hard':
        return `CONCEPTUAL LOAD: 3+ concepts. May require designing an approach or algorithm.
BOILERPLATE: Only minimal function stub. No hints. No explanation scaffolding.
TEST STRUCTURE: 1 visible test + 4 hidden tests (including edge + performance) = 5 total.
EDGE CASES: Null values, empty inputs, extreme numbers, duplicate logic traps, tie-breaking.
PERFORMANCE: Large input size. O(n²) solution MUST fail the hidden performance test.
TIME: 40-60 minutes to solve.
EXAMPLE PROBLEM SHAPE: "Find the top 3 customers by lifetime value, excluding churned accounts, with rank."
The student must design the approach, handle edge cases, and optimize.`

      default:
        return 'Use medium difficulty specification.'
    }
  }

  /**
   * Analyze the pedagogical value of user input
   */
  private async analyzePedagogicalValue(context: GenerationContext): Promise<PedagogicalAnalysis> {
    const analysisPrompt = `
You are an expert curriculum designer and educational psychologist. Analyze this learning request:

Type: ${context.type}
Language: ${context.language}  
Difficulty: ${context.difficulty}
User Request: "${context.userPrompt}"

Provide pedagogical analysis focusing on:
1. What is the user really trying to learn?
2. What foundational concepts should be reinforced?
3. What common misconceptions should be addressed?
4. How can this be made more engaging and practical?

Return JSON with this structure:
{
  "user_intent": "What the user wants to accomplish",
  "educational_gaps": ["Gap 1", "Gap 2"],
  "suggested_improvements": ["Improvement 1", "Improvement 2"],  
  "complexity_level": "appropriate|too_simple|too_complex",
  "recommendations": ["Rec 1", "Rec 2"]
}
`

    try {
      const messages = [{ role: 'user' as const, content: analysisPrompt }]
      return await this.aiService.generateJSON(messages, {
        temperature: 0.3 // Lower temperature for analysis
      }) as PedagogicalAnalysis
    } catch (error) {
      // Fallback analysis
      return {
        user_intent: context.userPrompt,
        educational_gaps: [],
        suggested_improvements: [],
        complexity_level: 'appropriate',
        recommendations: []
      }
    }
  }

  /**
   * Build the main idea generation prompt
   */
  private buildIdeaGenerationPrompt(
    context: GenerationContext, 
    analysis: PedagogicalAnalysis
  ): string {
    const difficultyGuidance = this.getDifficultyGuidance(context.difficulty)
    const typeGuidance = this.getTypeSpecificGuidance(context.type, context.language as CapsuleLanguage)
    const pedagogicalPrinciples = this.getPedagogicalPrinciples()

    return `
You are an expert curriculum designer creating educational ${context.type} problems for ${context.language}.

CONTEXT:
- User Request: "${context.userPrompt}"
- Target Difficulty: ${context.difficulty}
- Pedagogical Analysis: ${JSON.stringify(analysis, null, 2)}

EDUCATIONAL PRINCIPLES:
${pedagogicalPrinciples}

DIFFICULTY GUIDANCE:  
${difficultyGuidance}

TYPE-SPECIFIC GUIDANCE:
${typeGuidance}

Generate an educational problem that:
1. Addresses the user's request while maximizing learning value
2. Follows sound pedagogical principles
3. Is appropriate for the target difficulty level
4. Provides real-world context and motivation (why an engineer needs this skill)
5. Has a clear, actionable task

Return JSON matching this exact structure:
{
  "title": "Clear, specific title (max 60 chars)",
  "description": "Problem description that motivates and contextualizes the challenge",
  "context": "1-2 sentence real-world motivation. Why a working engineer would need this skill.",
  "task": "Direct, actionable build instruction. What the learner must do.",
  "insight": "The aha-moment revealed AFTER the learner passes all tests. A concise takeaway.",
  "real_world_usage": "Where this pattern appears in production.",
  "learning_objectives": [
    "Students will be able to...",
    "Students will understand..."
  ],
  "prerequisites": [
    "Basic concept 1",
    "Understanding of concept 2"  
  ],
  "difficulty_rationale": "Why this difficulty level is appropriate",
  "educational_value": 0.85,
  "estimated_time_minutes": 15,
  "target_audience": "Specific audience description",
  "key_concepts": [
    "Core concept 1",
    "Core concept 2"
  ]
}

IMPORTANT RULES:
- Do NOT include "Learning Objectives" or "Prerequisites" as sections in the description text
- The "context" field should read like a real engineering scenario, not an academic objective
- The "task" field should be a direct instruction ("Build...", "Implement...", "Write...")
- The "insight" field should be an engineering takeaway, not a learning objective

Focus on creating problems that are:
- Practical and applicable to real-world engineering scenarios
- Scaffolded appropriately for the difficulty level
- Engaging and motivating for learners
- Clear in their engineering context and task
`
  }

  /**
   * Get difficulty-specific guidance
   */
  private getDifficultyGuidance(difficulty: CapsuleDifficulty): string {
    switch (difficulty) {
      case 'easy':
        return `
EASY DIFFICULTY GUIDANCE:
- Focus on ONE core concept at a time
- Provide clear, step-by-step guidance  
- Use familiar, everyday examples
- Include helpful hints and scaffolding
- Avoid complex edge cases
- Ensure success is achievable for beginners
- Build confidence through clear wins`

      case 'medium':
        return `
MEDIUM DIFFICULTY GUIDANCE:
- Combine 2-3 related concepts
- Require some problem-solving thinking
- Include realistic complexity
- Balance guidance with independence
- Introduce common edge cases
- Encourage best practices
- Build on foundational knowledge`

      case 'hard':
        return `
HARD DIFFICULTY GUIDANCE:
- Integrate multiple complex concepts
- Require significant problem-solving
- Include challenging edge cases
- Minimal hints - encourage discovery
- Focus on optimization and efficiency
- Prepare for real-world complexity
- Challenge experienced learners`

      default:
        return 'Use appropriate difficulty level based on context.'
    }
  }

  /**
   * Get type and language specific guidance
   */
  private getTypeSpecificGuidance(type: CapsuleType, language: CapsuleLanguage): string {
    if (type === 'CODE') {
      return this.getCodeGuidance(language)
    } else if (type === 'DATABASE') {
      return this.getDatabaseGuidance()
    } else if (type === 'TERMINAL') {
      return this.getTerminalGuidance()
    }
    
    return ''
  }

  private getCodeGuidance(language: CapsuleLanguage): string {
    const languageSpecific = {
      python: 'Focus on Pythonic idioms, readability, and practical problem-solving',
      javascript: 'Emphasize functional programming, async patterns, and modern ES6+ features',
      java: 'Highlight object-oriented design, type safety, and enterprise patterns',
      sql: 'Focus on query optimization, data relationships, and analytical thinking',
      bash: 'Emphasize automation, file processing, and system administration tasks',
      go: 'Focus on concurrency, simplicity, and performance',
      csharp: 'Highlight .NET ecosystem, LINQ, and enterprise development patterns'
    }

    return `
CODE TYPE GUIDANCE:
- Create problems that teach programming concepts, not just syntax
- Include realistic scenarios that developers actually face
- Focus on problem-solving skills and logical thinking
- Encourage good coding practices and clean code
- ${languageSpecific[language] || 'Focus on best practices for the language'}

Educational priorities:
1. Conceptual understanding over memorization
2. Problem decomposition skills  
3. Pattern recognition
4. Debugging and troubleshooting
5. Code quality and maintainability`
  }

  private getDatabaseGuidance(): string {
    return `
DATABASE TYPE GUIDANCE:
- Create scenarios involving realistic business data
- Focus on data relationships and normalization
- Emphasize query optimization and performance
- Include data analysis and reporting aspects
- Teach both technical skills and analytical thinking

Educational priorities:
1. Understanding data relationships
2. Query design and optimization
3. Data integrity and constraints
4. Analytical thinking with data
5. Real-world business scenarios`
  }

  private getTerminalGuidance(): string {
    return `
TERMINAL TYPE GUIDANCE:
- Create practical system administration scenarios
- Focus on automation and efficiency
- Include file processing and text manipulation
- Emphasize understanding of Unix/Linux concepts
- Connect commands to real-world workflows

Educational priorities:
1. Command-line fluency
2. System administration concepts
3. Automation thinking
4. File and process management
5. Troubleshooting skills`
  }

  /**
   * Get core pedagogical principles
   */
  private getPedagogicalPrinciples(): string {
    return `
CORE PEDAGOGICAL PRINCIPLES:
1. Engineering Context: Every problem must have a real-world motivation
2. Scaffolding: Provide appropriate support and progression
3. Authentic Context: Use real-world, meaningful scenarios
4. Active Learning: Require learners to construct knowledge through practice
5. Feedback Loops: Design for immediate feedback and iteration
6. Transfer: Help learners apply concepts to new situations
7. Motivation: Create engaging, relevant challenges
8. Cognitive Load: Manage complexity appropriately for the learner level`
  }

  /**
   * Validate and enhance the generated idea
   */
  private validateAndEnhanceIdea(idea: CapsuleIdea, context: GenerationContext): CapsuleIdea {
    // Ensure educational value is reasonable
    if (idea.educational_value < 0.5) {
      idea.educational_value = 0.7 // Boost if too low
    }

    // Ensure time estimate is reasonable
    if (idea.estimated_time_minutes < 5) {
      idea.estimated_time_minutes = 10
    } else if (idea.estimated_time_minutes > 45) {
      idea.estimated_time_minutes = 30
    }

    // Ensure learning objectives exist
    if (!idea.learning_objectives || idea.learning_objectives.length === 0) {
      idea.learning_objectives = [
        `Students will be able to solve ${context.type.toLowerCase()} problems using ${context.language}`,
        `Students will understand the key concepts demonstrated in this exercise`
      ]
    }

    // Ensure prerequisites exist for non-easy difficulties
    if (context.difficulty !== 'easy' && (!idea.prerequisites || idea.prerequisites.length === 0)) {
      idea.prerequisites = [`Basic ${context.language} knowledge`]
    }

    return idea
  }

  /**
   * Set the AI service (injected dependency)
   */
  setAIService(aiService: any): void {
    this.aiService = aiService
  }

  /**
   * Get configuration
   */
  getConfig(): PedagogistConfig {
    return { ...this.config }
  }

  /**
   * Update configuration
   */
  updateConfig(updates: Partial<PedagogistConfig>): void {
    this.config = { ...this.config, ...updates }
  }
}

// ===== UTILITY FUNCTIONS =====

/**
 * Create a preconfigured pedagogist for different contexts
 */
export function createPedagogistAgent(context: {
  focusArea?: 'fundamentals' | 'advanced' | 'practical'
  audienceLevel?: 'beginner' | 'intermediate' | 'expert'
}): PedagogistAgent {
  let config: Partial<PedagogistConfig> = {}

  if (context.focusArea === 'fundamentals') {
    config = {
      focus_on_fundamentals: true,
      encourage_exploration: false,
      provide_context: true,
      difficulty_bias: 'easier'
    }
  } else if (context.focusArea === 'advanced') {
    config = {
      focus_on_fundamentals: false,
      encourage_exploration: true,
      provide_context: false,
      difficulty_bias: 'harder'
    }
  } else if (context.focusArea === 'practical') {
    config = {
      use_real_world_examples: true,
      provide_context: true,
      encourage_exploration: true
    }
  }

  return new PedagogistAgent(config)
}

/**
 * Validate that an idea meets educational standards
 */
export function validateEducationalIdea(idea: CapsuleIdea): {
  isValid: boolean
  issues: string[]
  suggestions: string[]
} {
  const issues: string[] = []
  const suggestions: string[] = []

  // Check learning objectives
  if (!idea.learning_objectives || idea.learning_objectives.length === 0) {
    issues.push('Missing learning objectives')
    suggestions.push('Add specific, measurable learning outcomes')
  }

  // Check educational value
  if (idea.educational_value < 0.6) {
    issues.push('Low educational value score')
    suggestions.push('Enhance the problem to provide more learning value')
  }

  // Check time estimate
  if (idea.estimated_time_minutes < 5 || idea.estimated_time_minutes > 60) {
    issues.push('Unrealistic time estimate')
    suggestions.push('Adjust complexity to fit 5-45 minute range')
  }

  // Check title clarity
  if (!idea.title || idea.title.length < 10) {
    issues.push('Title is too short or missing')
    suggestions.push('Provide a clear, descriptive title')
  }

  return {
    isValid: issues.length === 0,
    issues,
    suggestions
  }
}